// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package sweetrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConnectWpaNetworkResponse_WpaConnectionUpdateState int32

const (
	ConnectWpaNetworkResponse_CONNECTING ConnectWpaNetworkResponse_WpaConnectionUpdateState = 0
	ConnectWpaNetworkResponse_CONNECTED  ConnectWpaNetworkResponse_WpaConnectionUpdateState = 1
	ConnectWpaNetworkResponse_FAILED     ConnectWpaNetworkResponse_WpaConnectionUpdateState = 2
)

var ConnectWpaNetworkResponse_WpaConnectionUpdateState_name = map[int32]string{
	0: "CONNECTING",
	1: "CONNECTED",
	2: "FAILED",
}

var ConnectWpaNetworkResponse_WpaConnectionUpdateState_value = map[string]int32{
	"CONNECTING": 0,
	"CONNECTED":  1,
	"FAILED":     2,
}

func (x ConnectWpaNetworkResponse_WpaConnectionUpdateState) String() string {
	return proto.EnumName(ConnectWpaNetworkResponse_WpaConnectionUpdateState_name, int32(x))
}

func (ConnectWpaNetworkResponse_WpaConnectionUpdateState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5, 0}
}

type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

type GetInfoResponse struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Commit               string   `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *GetInfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetInfoResponse) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

type GetWpaConnectionInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWpaConnectionInfoRequest) Reset()         { *m = GetWpaConnectionInfoRequest{} }
func (m *GetWpaConnectionInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetWpaConnectionInfoRequest) ProtoMessage()    {}
func (*GetWpaConnectionInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *GetWpaConnectionInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWpaConnectionInfoRequest.Unmarshal(m, b)
}
func (m *GetWpaConnectionInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWpaConnectionInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetWpaConnectionInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWpaConnectionInfoRequest.Merge(m, src)
}
func (m *GetWpaConnectionInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetWpaConnectionInfoRequest.Size(m)
}
func (m *GetWpaConnectionInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWpaConnectionInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWpaConnectionInfoRequest proto.InternalMessageInfo

type GetWpaConnectionInfoResponse struct {
	Ssid                 string   `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWpaConnectionInfoResponse) Reset()         { *m = GetWpaConnectionInfoResponse{} }
func (m *GetWpaConnectionInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetWpaConnectionInfoResponse) ProtoMessage()    {}
func (*GetWpaConnectionInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *GetWpaConnectionInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWpaConnectionInfoResponse.Unmarshal(m, b)
}
func (m *GetWpaConnectionInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWpaConnectionInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetWpaConnectionInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWpaConnectionInfoResponse.Merge(m, src)
}
func (m *GetWpaConnectionInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetWpaConnectionInfoResponse.Size(m)
}
func (m *GetWpaConnectionInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWpaConnectionInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWpaConnectionInfoResponse proto.InternalMessageInfo

func (m *GetWpaConnectionInfoResponse) GetSsid() string {
	if m != nil {
		return m.Ssid
	}
	return ""
}

func (m *GetWpaConnectionInfoResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *GetWpaConnectionInfoResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *GetWpaConnectionInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ConnectWpaNetworkRequest struct {
	Ssid                 string   `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Psk                  string   `protobuf:"bytes,2,opt,name=psk,proto3" json:"psk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectWpaNetworkRequest) Reset()         { *m = ConnectWpaNetworkRequest{} }
func (m *ConnectWpaNetworkRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectWpaNetworkRequest) ProtoMessage()    {}
func (*ConnectWpaNetworkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *ConnectWpaNetworkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectWpaNetworkRequest.Unmarshal(m, b)
}
func (m *ConnectWpaNetworkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectWpaNetworkRequest.Marshal(b, m, deterministic)
}
func (m *ConnectWpaNetworkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectWpaNetworkRequest.Merge(m, src)
}
func (m *ConnectWpaNetworkRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectWpaNetworkRequest.Size(m)
}
func (m *ConnectWpaNetworkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectWpaNetworkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectWpaNetworkRequest proto.InternalMessageInfo

func (m *ConnectWpaNetworkRequest) GetSsid() string {
	if m != nil {
		return m.Ssid
	}
	return ""
}

func (m *ConnectWpaNetworkRequest) GetPsk() string {
	if m != nil {
		return m.Psk
	}
	return ""
}

type ConnectWpaNetworkResponse struct {
	Status               ConnectWpaNetworkResponse_WpaConnectionUpdateState `protobuf:"varint,1,opt,name=status,proto3,enum=sweetrpc.ConnectWpaNetworkResponse_WpaConnectionUpdateState" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *ConnectWpaNetworkResponse) Reset()         { *m = ConnectWpaNetworkResponse{} }
func (m *ConnectWpaNetworkResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectWpaNetworkResponse) ProtoMessage()    {}
func (*ConnectWpaNetworkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *ConnectWpaNetworkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectWpaNetworkResponse.Unmarshal(m, b)
}
func (m *ConnectWpaNetworkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectWpaNetworkResponse.Marshal(b, m, deterministic)
}
func (m *ConnectWpaNetworkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectWpaNetworkResponse.Merge(m, src)
}
func (m *ConnectWpaNetworkResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectWpaNetworkResponse.Size(m)
}
func (m *ConnectWpaNetworkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectWpaNetworkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectWpaNetworkResponse proto.InternalMessageInfo

func (m *ConnectWpaNetworkResponse) GetStatus() ConnectWpaNetworkResponse_WpaConnectionUpdateState {
	if m != nil {
		return m.Status
	}
	return ConnectWpaNetworkResponse_CONNECTING
}

type WpaNetwork struct {
	Bssid                string   `protobuf:"bytes,1,opt,name=bssid,proto3" json:"bssid,omitempty"`
	Frequency            string   `protobuf:"bytes,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	SignalLevel          string   `protobuf:"bytes,3,opt,name=signal_level,json=signalLevel,proto3" json:"signal_level,omitempty"`
	Flags                string   `protobuf:"bytes,4,opt,name=flags,proto3" json:"flags,omitempty"`
	Ssid                 string   `protobuf:"bytes,5,opt,name=ssid,proto3" json:"ssid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WpaNetwork) Reset()         { *m = WpaNetwork{} }
func (m *WpaNetwork) String() string { return proto.CompactTextString(m) }
func (*WpaNetwork) ProtoMessage()    {}
func (*WpaNetwork) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *WpaNetwork) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WpaNetwork.Unmarshal(m, b)
}
func (m *WpaNetwork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WpaNetwork.Marshal(b, m, deterministic)
}
func (m *WpaNetwork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WpaNetwork.Merge(m, src)
}
func (m *WpaNetwork) XXX_Size() int {
	return xxx_messageInfo_WpaNetwork.Size(m)
}
func (m *WpaNetwork) XXX_DiscardUnknown() {
	xxx_messageInfo_WpaNetwork.DiscardUnknown(m)
}

var xxx_messageInfo_WpaNetwork proto.InternalMessageInfo

func (m *WpaNetwork) GetBssid() string {
	if m != nil {
		return m.Bssid
	}
	return ""
}

func (m *WpaNetwork) GetFrequency() string {
	if m != nil {
		return m.Frequency
	}
	return ""
}

func (m *WpaNetwork) GetSignalLevel() string {
	if m != nil {
		return m.SignalLevel
	}
	return ""
}

func (m *WpaNetwork) GetFlags() string {
	if m != nil {
		return m.Flags
	}
	return ""
}

func (m *WpaNetwork) GetSsid() string {
	if m != nil {
		return m.Ssid
	}
	return ""
}

type GetWpaNetworksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWpaNetworksRequest) Reset()         { *m = GetWpaNetworksRequest{} }
func (m *GetWpaNetworksRequest) String() string { return proto.CompactTextString(m) }
func (*GetWpaNetworksRequest) ProtoMessage()    {}
func (*GetWpaNetworksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *GetWpaNetworksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWpaNetworksRequest.Unmarshal(m, b)
}
func (m *GetWpaNetworksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWpaNetworksRequest.Marshal(b, m, deterministic)
}
func (m *GetWpaNetworksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWpaNetworksRequest.Merge(m, src)
}
func (m *GetWpaNetworksRequest) XXX_Size() int {
	return xxx_messageInfo_GetWpaNetworksRequest.Size(m)
}
func (m *GetWpaNetworksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWpaNetworksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWpaNetworksRequest proto.InternalMessageInfo

type GetWpaNetworksResponse struct {
	Networks             []*WpaNetwork `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetWpaNetworksResponse) Reset()         { *m = GetWpaNetworksResponse{} }
func (m *GetWpaNetworksResponse) String() string { return proto.CompactTextString(m) }
func (*GetWpaNetworksResponse) ProtoMessage()    {}
func (*GetWpaNetworksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *GetWpaNetworksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWpaNetworksResponse.Unmarshal(m, b)
}
func (m *GetWpaNetworksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWpaNetworksResponse.Marshal(b, m, deterministic)
}
func (m *GetWpaNetworksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWpaNetworksResponse.Merge(m, src)
}
func (m *GetWpaNetworksResponse) XXX_Size() int {
	return xxx_messageInfo_GetWpaNetworksResponse.Size(m)
}
func (m *GetWpaNetworksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWpaNetworksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWpaNetworksResponse proto.InternalMessageInfo

func (m *GetWpaNetworksResponse) GetNetworks() []*WpaNetwork {
	if m != nil {
		return m.Networks
	}
	return nil
}

type UpdateRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

type ConnectToRemoteNodeRequest struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Cert                 []byte   `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	Macaroon             []byte   `protobuf:"bytes,3,opt,name=macaroon,proto3" json:"macaroon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectToRemoteNodeRequest) Reset()         { *m = ConnectToRemoteNodeRequest{} }
func (m *ConnectToRemoteNodeRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectToRemoteNodeRequest) ProtoMessage()    {}
func (*ConnectToRemoteNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *ConnectToRemoteNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectToRemoteNodeRequest.Unmarshal(m, b)
}
func (m *ConnectToRemoteNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectToRemoteNodeRequest.Marshal(b, m, deterministic)
}
func (m *ConnectToRemoteNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectToRemoteNodeRequest.Merge(m, src)
}
func (m *ConnectToRemoteNodeRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectToRemoteNodeRequest.Size(m)
}
func (m *ConnectToRemoteNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectToRemoteNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectToRemoteNodeRequest proto.InternalMessageInfo

func (m *ConnectToRemoteNodeRequest) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *ConnectToRemoteNodeRequest) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *ConnectToRemoteNodeRequest) GetMacaroon() []byte {
	if m != nil {
		return m.Macaroon
	}
	return nil
}

type ConnectToRemoteNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectToRemoteNodeResponse) Reset()         { *m = ConnectToRemoteNodeResponse{} }
func (m *ConnectToRemoteNodeResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectToRemoteNodeResponse) ProtoMessage()    {}
func (*ConnectToRemoteNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12}
}

func (m *ConnectToRemoteNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectToRemoteNodeResponse.Unmarshal(m, b)
}
func (m *ConnectToRemoteNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectToRemoteNodeResponse.Marshal(b, m, deterministic)
}
func (m *ConnectToRemoteNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectToRemoteNodeResponse.Merge(m, src)
}
func (m *ConnectToRemoteNodeResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectToRemoteNodeResponse.Size(m)
}
func (m *ConnectToRemoteNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectToRemoteNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectToRemoteNodeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("sweetrpc.ConnectWpaNetworkResponse_WpaConnectionUpdateState", ConnectWpaNetworkResponse_WpaConnectionUpdateState_name, ConnectWpaNetworkResponse_WpaConnectionUpdateState_value)
	proto.RegisterType((*GetInfoRequest)(nil), "sweetrpc.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "sweetrpc.GetInfoResponse")
	proto.RegisterType((*GetWpaConnectionInfoRequest)(nil), "sweetrpc.GetWpaConnectionInfoRequest")
	proto.RegisterType((*GetWpaConnectionInfoResponse)(nil), "sweetrpc.GetWpaConnectionInfoResponse")
	proto.RegisterType((*ConnectWpaNetworkRequest)(nil), "sweetrpc.ConnectWpaNetworkRequest")
	proto.RegisterType((*ConnectWpaNetworkResponse)(nil), "sweetrpc.ConnectWpaNetworkResponse")
	proto.RegisterType((*WpaNetwork)(nil), "sweetrpc.WpaNetwork")
	proto.RegisterType((*GetWpaNetworksRequest)(nil), "sweetrpc.GetWpaNetworksRequest")
	proto.RegisterType((*GetWpaNetworksResponse)(nil), "sweetrpc.GetWpaNetworksResponse")
	proto.RegisterType((*UpdateRequest)(nil), "sweetrpc.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "sweetrpc.UpdateResponse")
	proto.RegisterType((*ConnectToRemoteNodeRequest)(nil), "sweetrpc.ConnectToRemoteNodeRequest")
	proto.RegisterType((*ConnectToRemoteNodeResponse)(nil), "sweetrpc.ConnectToRemoteNodeResponse")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 597 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x6e, 0xfa, 0xb7, 0xf6, 0xac, 0x2b, 0xc1, 0x94, 0x2d, 0x0b, 0x43, 0x74, 0x86, 0xa1, 0x5d,
	0x55, 0xa8, 0xdc, 0x82, 0x34, 0xd4, 0x95, 0xaa, 0x68, 0x2a, 0x52, 0xd6, 0x69, 0x17, 0x48, 0x43,
	0x59, 0xea, 0x56, 0xd1, 0xda, 0x38, 0xd8, 0xee, 0x26, 0x1e, 0x02, 0x9e, 0x87, 0xc7, 0x43, 0x8e,
	0x9d, 0xa4, 0x69, 0x53, 0xc6, 0x9d, 0xcf, 0xef, 0xf7, 0x9d, 0x2f, 0xe7, 0x04, 0xea, 0x2c, 0xf4,
	0x3a, 0x21, 0xa3, 0x82, 0xa2, 0x1a, 0x7f, 0x20, 0x44, 0xb0, 0xd0, 0xc3, 0x26, 0x34, 0x07, 0x44,
	0x0c, 0x83, 0x29, 0x75, 0xc8, 0x8f, 0x25, 0xe1, 0x02, 0x7f, 0x83, 0x27, 0x89, 0x87, 0x87, 0x34,
	0xe0, 0x04, 0xed, 0x43, 0x95, 0x13, 0xe6, 0xbb, 0x73, 0xcb, 0x68, 0x1b, 0xa7, 0x75, 0x47, 0x5b,
	0xc8, 0x82, 0x9d, 0x7b, 0xc2, 0xb8, 0x4f, 0x03, 0xab, 0x18, 0x05, 0x62, 0x53, 0x56, 0x78, 0x74,
	0xb1, 0xf0, 0x85, 0x55, 0x52, 0x15, 0xca, 0xc2, 0x2f, 0xe1, 0xc5, 0x80, 0x88, 0xeb, 0xd0, 0xed,
	0xd1, 0x20, 0x20, 0x9e, 0xf0, 0x69, 0xb0, 0x8a, 0xcd, 0xe0, 0x28, 0x3f, 0xac, 0x89, 0x20, 0x28,
	0x73, 0xee, 0x4f, 0x34, 0x8d, 0xe8, 0x8d, 0x5a, 0x50, 0xe1, 0xc2, 0x15, 0x44, 0x53, 0x50, 0x06,
	0x6a, 0x42, 0xd1, 0x0f, 0x35, 0x78, 0xd1, 0x0f, 0x25, 0xd5, 0x05, 0xe1, 0xdc, 0x9d, 0x11, 0xab,
	0xac, 0xa8, 0x6a, 0x13, 0x9f, 0x81, 0xa5, 0xd1, 0xae, 0x43, 0x77, 0x44, 0xc4, 0x03, 0x65, 0x77,
	0x9a, 0x4f, 0x2e, 0x9e, 0x09, 0xa5, 0x90, 0xdf, 0x69, 0x34, 0xf9, 0xc4, 0x7f, 0x0c, 0x38, 0xcc,
	0x69, 0xa1, 0x39, 0x8f, 0xa1, 0x2a, 0x29, 0x2d, 0x79, 0xd4, 0xa5, 0xd9, 0xfd, 0xd0, 0x89, 0xc5,
	0xef, 0x6c, 0x2d, 0xea, 0x64, 0x24, 0xb8, 0x0a, 0x27, 0xae, 0x20, 0x97, 0x72, 0x2e, 0x47, 0xf7,
	0xc2, 0x7d, 0xb0, 0xb6, 0xe5, 0xa0, 0x26, 0x40, 0xef, 0xeb, 0x68, 0xd4, 0xef, 0x8d, 0x87, 0xa3,
	0x81, 0x59, 0x40, 0x7b, 0x50, 0xd7, 0x76, 0xff, 0xdc, 0x34, 0x10, 0x40, 0xf5, 0xf3, 0xa7, 0xe1,
	0x45, 0xff, 0xdc, 0x2c, 0xe2, 0x5f, 0x06, 0x40, 0x0a, 0x2f, 0xb5, 0xbc, 0x5d, 0x19, 0x58, 0x19,
	0xe8, 0x08, 0xea, 0x53, 0x26, 0x15, 0x09, 0xbc, 0x9f, 0x7a, 0xee, 0xd4, 0x81, 0x8e, 0xa1, 0xc1,
	0xfd, 0x59, 0xe0, 0xce, 0xbf, 0xcf, 0xc9, 0x3d, 0x99, 0x6b, 0xcd, 0x77, 0x95, 0xef, 0x42, 0xba,
	0x64, 0xdb, 0xe9, 0xdc, 0x9d, 0x71, 0x2d, 0xbd, 0x32, 0x12, 0x71, 0x2b, 0xa9, 0xb8, 0xf8, 0x00,
	0x9e, 0xab, 0x05, 0xd0, 0x8c, 0x78, 0xbc, 0x19, 0x5f, 0x60, 0x7f, 0x3d, 0xa0, 0xf5, 0x7d, 0x07,
	0xb5, 0x40, 0xfb, 0x2c, 0xa3, 0x5d, 0x3a, 0xdd, 0xed, 0xb6, 0x52, 0x85, 0x57, 0xa4, 0x4d, 0xb2,
	0xf0, 0x31, 0xec, 0x29, 0xb9, 0xe2, 0xcf, 0x6c, 0x42, 0x69, 0xc9, 0xe2, 0xe5, 0x96, 0x4f, 0x79,
	0x16, 0x71, 0x8a, 0x82, 0xc1, 0x37, 0x60, 0x6b, 0xb5, 0xc7, 0xd4, 0x21, 0x0b, 0x2a, 0xc8, 0x88,
	0x4e, 0xb2, 0x1d, 0xfc, 0xb4, 0x83, 0x2f, 0xa7, 0xf3, 0x08, 0x13, 0x91, 0x5e, 0x0d, 0x27, 0x7a,
	0x23, 0x1b, 0x6a, 0x0b, 0xd7, 0x73, 0x19, 0xa5, 0x41, 0x24, 0x53, 0xc3, 0x49, 0x6c, 0x79, 0x19,
	0xb9, 0xfd, 0x15, 0x7c, 0xf7, 0x77, 0x19, 0x2a, 0x97, 0x72, 0x2a, 0x74, 0x06, 0x3b, 0xfa, 0x3e,
	0x91, 0x95, 0x0e, 0x9a, 0x3d, 0x62, 0xfb, 0x30, 0x27, 0xa2, 0x07, 0x29, 0xa0, 0x19, 0xb4, 0xf2,
	0xae, 0x0c, 0x9d, 0x64, 0x8a, 0xb6, 0x1d, 0xa9, 0xfd, 0xf6, 0xb1, 0xb4, 0x04, 0xe8, 0x06, 0x9e,
	0x6e, 0xac, 0x38, 0xc2, 0xff, 0xdc, 0x7f, 0x05, 0xf1, 0xfa, 0x3f, 0x6e, 0x04, 0x17, 0xd0, 0x55,
	0xf4, 0xf3, 0x5a, 0x59, 0x0a, 0xf4, 0x6a, 0x9d, 0xdb, 0xda, 0x1e, 0xd9, 0xed, 0xed, 0x09, 0x49,
	0xdb, 0x8f, 0x50, 0x55, 0x1f, 0x1f, 0x1d, 0xa4, 0xd9, 0x99, 0x8d, 0xb1, 0xad, 0xcd, 0x40, 0x52,
	0x3e, 0x81, 0x67, 0x39, 0x5f, 0x12, 0xbd, 0xd9, 0x98, 0x29, 0x67, 0x91, 0xec, 0x93, 0x47, 0xb2,
	0x62, 0x94, 0xdb, 0x6a, 0xf4, 0x27, 0x7f, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0x44, 0xd2, 0x91,
	0x62, 0xd6, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SweetClient is the client API for Sweet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SweetClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	GetWpaConnectionInfo(ctx context.Context, in *GetWpaConnectionInfoRequest, opts ...grpc.CallOption) (*GetWpaConnectionInfoResponse, error)
	ConnectWpaNetwork(ctx context.Context, in *ConnectWpaNetworkRequest, opts ...grpc.CallOption) (*ConnectWpaNetworkResponse, error)
	GetWpaNetworks(ctx context.Context, in *GetWpaNetworksRequest, opts ...grpc.CallOption) (*GetWpaNetworksResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	ConnectToRemoteNode(ctx context.Context, in *ConnectToRemoteNodeRequest, opts ...grpc.CallOption) (*ConnectToRemoteNodeResponse, error)
}

type sweetClient struct {
	cc *grpc.ClientConn
}

func NewSweetClient(cc *grpc.ClientConn) SweetClient {
	return &sweetClient{cc}
}

func (c *sweetClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, "/sweetrpc.Sweet/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sweetClient) GetWpaConnectionInfo(ctx context.Context, in *GetWpaConnectionInfoRequest, opts ...grpc.CallOption) (*GetWpaConnectionInfoResponse, error) {
	out := new(GetWpaConnectionInfoResponse)
	err := c.cc.Invoke(ctx, "/sweetrpc.Sweet/GetWpaConnectionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sweetClient) ConnectWpaNetwork(ctx context.Context, in *ConnectWpaNetworkRequest, opts ...grpc.CallOption) (*ConnectWpaNetworkResponse, error) {
	out := new(ConnectWpaNetworkResponse)
	err := c.cc.Invoke(ctx, "/sweetrpc.Sweet/ConnectWpaNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sweetClient) GetWpaNetworks(ctx context.Context, in *GetWpaNetworksRequest, opts ...grpc.CallOption) (*GetWpaNetworksResponse, error) {
	out := new(GetWpaNetworksResponse)
	err := c.cc.Invoke(ctx, "/sweetrpc.Sweet/GetWpaNetworks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sweetClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/sweetrpc.Sweet/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sweetClient) ConnectToRemoteNode(ctx context.Context, in *ConnectToRemoteNodeRequest, opts ...grpc.CallOption) (*ConnectToRemoteNodeResponse, error) {
	out := new(ConnectToRemoteNodeResponse)
	err := c.cc.Invoke(ctx, "/sweetrpc.Sweet/ConnectToRemoteNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SweetServer is the server API for Sweet service.
type SweetServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	GetWpaConnectionInfo(context.Context, *GetWpaConnectionInfoRequest) (*GetWpaConnectionInfoResponse, error)
	ConnectWpaNetwork(context.Context, *ConnectWpaNetworkRequest) (*ConnectWpaNetworkResponse, error)
	GetWpaNetworks(context.Context, *GetWpaNetworksRequest) (*GetWpaNetworksResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	ConnectToRemoteNode(context.Context, *ConnectToRemoteNodeRequest) (*ConnectToRemoteNodeResponse, error)
}

func RegisterSweetServer(s *grpc.Server, srv SweetServer) {
	s.RegisterService(&_Sweet_serviceDesc, srv)
}

func _Sweet_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SweetServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sweetrpc.Sweet/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SweetServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sweet_GetWpaConnectionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWpaConnectionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SweetServer).GetWpaConnectionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sweetrpc.Sweet/GetWpaConnectionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SweetServer).GetWpaConnectionInfo(ctx, req.(*GetWpaConnectionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sweet_ConnectWpaNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectWpaNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SweetServer).ConnectWpaNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sweetrpc.Sweet/ConnectWpaNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SweetServer).ConnectWpaNetwork(ctx, req.(*ConnectWpaNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sweet_GetWpaNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWpaNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SweetServer).GetWpaNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sweetrpc.Sweet/GetWpaNetworks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SweetServer).GetWpaNetworks(ctx, req.(*GetWpaNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sweet_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SweetServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sweetrpc.Sweet/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SweetServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sweet_ConnectToRemoteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectToRemoteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SweetServer).ConnectToRemoteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sweetrpc.Sweet/ConnectToRemoteNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SweetServer).ConnectToRemoteNode(ctx, req.(*ConnectToRemoteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sweet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sweetrpc.Sweet",
	HandlerType: (*SweetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Sweet_GetInfo_Handler,
		},
		{
			MethodName: "GetWpaConnectionInfo",
			Handler:    _Sweet_GetWpaConnectionInfo_Handler,
		},
		{
			MethodName: "ConnectWpaNetwork",
			Handler:    _Sweet_ConnectWpaNetwork_Handler,
		},
		{
			MethodName: "GetWpaNetworks",
			Handler:    _Sweet_GetWpaNetworks_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Sweet_Update_Handler,
		},
		{
			MethodName: "ConnectToRemoteNode",
			Handler:    _Sweet_ConnectToRemoteNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
