#!/bin/sh

# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
  set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi

### BEGIN INIT INFO
# Provides:          sweetd
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Bitcoin candy dispenser daemon
# Description:       Manages pairing and control of the Bitcoin candy dispenser
### END INIT INFO

DESC="Manages pairing and control of the Bitcoin candy dispenser"
NAME=sweetd
DAEMON=/usr/local/bin/sweetd
DEFAULTS=/etc/default/sweetd
PIDFILE=/var/run/sweetd.pid
SCRIPTNAME=/etc/init.d/$NAME
EXTRA_OPTS=

test -f $DAEMON || exit 0

[ -s "$DEFAULTS" ] && . /etc/default/sweetd

. /lib/lsb/init-functions

case "$1" in
start)  log_daemon_msg "Starting sweetd" "sweetd"
        start-stop-daemon --start -b -C --oknodo --exec $DAEMON --pidfile $PIDFILE --make-pidfile -- $EXTRA_OPTS
        log_end_msg $?
        ;;
stop)   log_daemon_msg "Stopping sweetd" "sweetd"
        start-stop-daemon --stop --oknodo --pidfile $PIDFILE --name $NAME
        log_end_msg $?
        rm -f $PIDFILE
        ;;
restart) log_daemon_msg "Restarting sweetd" $NAME
        $0 stop
        $0 start
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)      log_action_msg "Usage: $SCRIPTNAME {start|stop|status|restart}"
        exit 2
        ;;
esac
exit 0